version: "3.9"
services:
 eurekaserver02:
  image: eurekaserver:v1
  container_name: eurekaserver02
  ports: 
   - "9003:8899"
  #links:
  # - 
  environment:
   - variable1=valor1
   - variable2=valor2
#creamos un volumen de tipo host
  volumes:
   - /home/neo/temp/docker/var/apps/eurekaserver02/conf:/conf
